inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  NewCops: disable

Metrics/MethodLength:
  Max: 20

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Layout/LineLength:
  Exclude:
    - 'test/test_helper.rb'
    - 'spec/support/omni_auth_mock_helper.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/application_controller.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/application_controller.rb'

Metrics/BlockLength:
  IgnoredMethods: ['describe']
