name: Release and Update Manifests

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      ecr_repository:
        required: true
        type: string
        description: 'This projects ecr repo e.g. platform-console'
      manifests_directory:
        required: true
        type: string
        description: 'Root path for this app in the manifests repo e.g. vsp-tools-backend/platform-console-api'
      environments:
       required: true # utility
       type: string
       description: 'Root path for this app in the manifests repo e.g. '

  workflow_call:
    inputs:
      ecr_repository:
        required: true #platform-console
        type: string
      manifests_directory:
        required: true #${{inputs.manifests_directory}}
        type: string
      auto_deploy_envs:
       required: true # utility
       type: string
    secrets:
      aws_access_key_id: #${{ secrets.AWS_ACCESS_KEY_ID }}
        required: true
      aws_secret_access_key: #${{ secrets.AWS_SECRET_ACCESS_KEY }}
        required: true

jobs:
  prepare-values:
    runs-on: ubuntu-20.04
    outputs:
      environments: ${{ steps.set-environments.outputs.environments }}
    steps:
      - name: Set to auto deploy environments when not run via workflow dispatch
        if: github.event.inputs.environments == ''
        run: |
         echo "triggered via schedule"
         echo "environments=${{inputs.auto_deploy_envs}}" >> $GITHUB_ENV
      - name: Set to environments specified in input when run via workflow dispatch
        if: github.event.inputs.environments != ''
        run: |
          echo "triggered via workflow dispatch"
          echo "environments=${{ github.event.inputs.environments }}" >> $GITHUB_ENV
      - name: Set output
        id: set-environments
        run: |
          echo "::set-output name=environments::${{ github.event.inputs.auto_deploy_envs }}"
  release:
    needs: [prepare-values]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        if: steps.semantic.outputs.new_release_published == 'true' && github.event.inputs.environments == ''
        # use secrets passed into template
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: "us-gov-west-1"
        if: github.event.inputs.environments != ''
        # use secrets from repo - this is a manual workflow_dispatch call
        with:
          aws-access-key-id: ${{ SECRETS.aws_access_key_id }}
          aws-secret-access-key: ${{ SECRETS.aws_secret_access_key }}
          aws-region: "us-gov-west-1"
      - name: Log into ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Get bot token from Parameter Store
        uses: marvinpinto/action-inject-ssm-secrets@latest
        with:
          ssm_parameter: /devops/VA_VSP_BOT_GITHUB_TOKEN
          env_variable_name: VA_VSP_BOT_GITHUB_TOKEN
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        env:
          GITHUB_TOKEN: ${{ env.VA_VSP_BOT_GITHUB_TOKEN }}
      - name: Install yq if needed
        if: steps.semantic.outputs.new_release_published == 'true' || github.event.inputs.environments != ''
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys CC86BB64
          sudo add-apt-repository ppa:rmescandon/yq
          sudo apt update
          sudo apt install yq -y
      - name: Check out Manifest Repo
        uses: actions/checkout@v2
        with:
          repository: department-of-veterans-affairs/vsp-infra-application-manifests
          token: ${{ env.VA_VSP_BOT_GITHUB_TOKEN }}
          fetch-depth: 1
          path: vsp-infra-application-manifests
      - name: Update image name in Manifest repo
        if: steps.semantic.outputs.new_release_published == 'true' || github.event.inputs.environments != ''
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dsva/${{inputs.ecr_repository}}
        run: |
          cd vsp-infra-application-manifests/apps/${{inputs.manifests_directory}}
          # Update ecr image
          envs=( ${{ needs.prepare-values.outputs.environments }} )
          for env in ${envs[*]};
          do
            yq e -i '.spec.template.spec.containers.[0].image = "008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/${{inputs.ecr_repository}}:${{inputs.ecr_repository}}-${{ github.sha }}"' $env/deployment.yml
          done
          git diff
      - name: Add and Commit file
        if: steps.semantic.outputs.new_release_published == 'true' || github.event.inputs.environments != ''
        uses: EndBug/add-and-commit@v7
        with:
          branch: main
          add: '*'
          cwd: vsp-infra-application-manifests/apps/${{inputs.manifests_directory}}
          author_name: va-vsp-bot
          author_email: devops@va.gov
          message: 'Release ${{ needs.prepare-values.outputs.environments }} for ${{inputs.ecr_repository}}.'
