name: Release and Update Manifests

on:
  push:
    branches:
      - master
  workflow_dispatch:
  workflow_run:
    workflows: ["Push image to ECR when changes are pushed to master"]
    types: [completed]

jobs:
  deploy:
    uses: department-of-veterans-affairs/platform-console-api/.github/workflows/deploy-template.yml@master
    with:
      ecr_repository: 'platform-console'
      manifests_directory: 'vsp-tools-backend/platform-console-api'
      auto_deploy_envs: 'utility'
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
