# name: Release and Update Manifests
# on:
#  push:
#    branches:
#      - lhattamer-gha-reusable-workflows
# deploy:
#   uses: department-of-veterans-affairs/platform-console-api/.github/workflows/eploy-template.yml@master
#   with:
#     ecr_repository: 'platform-console'
#     manifests_directory: 'vsp-tools-backend/platform-console-api'
#     auto_deploy_envs: 'utility'
#   secrets:
#     aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}



name: Release and Update Manifests
on:
 push:
   branches:
     - lhattamer-gha-reusable-workflows

jobs:
  deploy:
    uses: department-of-veterans-affairs/platform-console-api/.github/workflows/deploy-template.yml@lhattamer-gha-reusable-workflows
    with:
      ecr_repository: 'platform-console'
      manifests_directory: 'vsp-tools-backend/platform-console-api'
      auto_deploy_envs: 'utility'
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }