name: Push image to ECR when changes are pushed to master

on:
 push:
   branches:
     - master
 workflow_dispatch:

 # Edit this var to point to your apps ECR repo
 env:
   ecrRepository: 'dsva/platform-console'

jobs:
  prepare-build:
    name: Prepare build for image push to ECR
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Capture argo image versions
        id: componentVersions
        run: |
          echo "::set-output name=config::$(jq -c .components versions.json)"
      - name: Upload versions file
        uses: actions/upload-artifact@v2
        with:
          name: versions
          path: versions.json
    outputs:
      config: ${{ steps.componentVersions.outputs.config }}

  push-image:
    runs-on: ubuntu-20.04
    name: Push image to ECR
    needs: prepare-build
    strategy:
      matrix:
        versions: ${{ fromJson(needs.prepare-build.outputs.config) }}
    steps:
      - uses: actions/checkout@v2
      - name: Build and push argo images to ECR
        uses: kciter/aws-ecr-action@v4
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: '008577686731'
          repo: $ecrRepository
          region: us-gov-west-1
          tags: "${{ matrix.versions['name']}}-${{ matrix.versions['version'] }}-${{ github.sha }}"
          dockerfile: Dockerfile
          extra_build_args: "--build-arg RAILS_ENV=production"
